PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS source_file(file_id TEXT PRIMARY KEY, source_id TEXT, logical_path TEXT, real_path TEXT, extension TEXT, lane TEXT, size_bytes INTEGER, raw_file_sha256 TEXT, parse_status TEXT, semantic_status TEXT, review_reason TEXT);
CREATE TABLE IF NOT EXISTS source_byte_coverage(coverage_id TEXT PRIMARY KEY, file_id TEXT, coverage_status TEXT, bytes_total INTEGER, bytes_accounted INTEGER, reason TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS code_repo(repo_id TEXT PRIMARY KEY, source_id TEXT, repo_path TEXT, sanitized_remote_url TEXT, default_branch TEXT, current_branch TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS git_remote(remote_id TEXT PRIMARY KEY, repo_id TEXT, remote_name TEXT, sanitized_url TEXT);
CREATE TABLE IF NOT EXISTS git_branch(branch_id TEXT PRIMARY KEY, repo_id TEXT, branch_name TEXT, is_current INTEGER, commit_count INTEGER);
CREATE TABLE IF NOT EXISTS git_commit(commit_sha TEXT PRIMARY KEY, short_sha TEXT, repo_id TEXT, branch_id TEXT, parent_sha_list TEXT, author_name TEXT, author_email_hash_or_redacted TEXT, commit_time TEXT, message_subject TEXT, message_body TEXT, is_merge INTEGER, commit_order INTEGER);
CREATE TABLE IF NOT EXISTS git_file_change(change_id TEXT PRIMARY KEY, commit_sha TEXT, file_id TEXT, old_path TEXT, new_path TEXT, change_type TEXT, insertions INTEGER, deletions INTEGER, before_file_sha TEXT, after_file_sha TEXT);
CREATE TABLE IF NOT EXISTS code_file(file_id TEXT PRIMARY KEY, source_id TEXT, canonical_path TEXT, current_path TEXT, language TEXT, extension TEXT, first_seen_commit_sha TEXT, last_seen_commit_sha TEXT, current_sha256 TEXT, is_active INTEGER);
CREATE TABLE IF NOT EXISTS code_file_version(file_version_id TEXT PRIMARY KEY, file_id TEXT, commit_sha TEXT, path_at_commit TEXT, raw_file_sha256 TEXT, normalized_text_sha256 TEXT, language TEXT, extension TEXT, line_count INTEGER, byte_count INTEGER, is_deleted INTEGER, is_renamed INTEGER, created_at TEXT);
CREATE TABLE IF NOT EXISTS code_line_snapshot(line_id TEXT PRIMARY KEY, file_version_id TEXT, file_id TEXT, commit_sha TEXT, line_number INTEGER, line_text TEXT, line_sha256 TEXT, normalized_line_sha256 TEXT, indent_level INTEGER, is_blank INTEGER, is_comment INTEGER, search_text TEXT);
CREATE TABLE IF NOT EXISTS code_chunk(chunk_id TEXT PRIMARY KEY, chunk_sha256 TEXT, file_version_id TEXT, file_id TEXT, commit_sha TEXT, chunk_type TEXT, language TEXT, start_line INTEGER, end_line INTEGER, chunk_text TEXT, symbol_id TEXT, route_id TEXT, parent_chunk_id TEXT, search_text TEXT);
CREATE TABLE IF NOT EXISTS code_symbol(symbol_id TEXT PRIMARY KEY, symbol_name TEXT, symbol_type TEXT, file_version_id TEXT, file_id TEXT, commit_sha TEXT, language TEXT, start_line INTEGER, end_line INTEGER, signature TEXT, symbol_sha256 TEXT, docstring_or_comment TEXT, exported_bool INTEGER);
CREATE TABLE IF NOT EXISTS app_route(route_id TEXT PRIMARY KEY, route_path TEXT, route_type TEXT, framework_guess TEXT, file_id TEXT, file_version_id TEXT, commit_sha TEXT, handler_symbol_id TEXT, method TEXT, input_contract TEXT, output_contract TEXT, route_sha256 TEXT);
CREATE TABLE IF NOT EXISTS dependency_manifest(manifest_id TEXT PRIMARY KEY, file_id TEXT, manifest_type TEXT, ecosystem TEXT, path TEXT, commit_sha TEXT, sha256 TEXT);
CREATE TABLE IF NOT EXISTS dependency_item(dependency_id TEXT PRIMARY KEY, manifest_id TEXT, package_name TEXT, version_spec TEXT, ecosystem TEXT, dev_or_runtime TEXT, source_file_id TEXT, commit_sha TEXT);
CREATE TABLE IF NOT EXISTS code_dependency_edge(edge_id TEXT PRIMARY KEY, from_type TEXT, from_id TEXT, to_type TEXT, to_id TEXT, edge_type TEXT, confidence REAL, source_chunk_id TEXT, commit_sha TEXT);
CREATE TABLE IF NOT EXISTS project_artifact(artifact_id TEXT PRIMARY KEY, source_file_id TEXT, artifact_type TEXT, artifact_sha256 TEXT, path TEXT, created_by_commit_sha TEXT, linked_route_id TEXT, linked_symbol_id TEXT, metadata_json TEXT, semantic_status TEXT);
CREATE TABLE IF NOT EXISTS artifact_relation_edge(edge_id TEXT PRIMARY KEY, artifact_id TEXT, related_entity_type TEXT, related_entity_id TEXT, relation_type TEXT, commit_sha TEXT, confidence REAL);
CREATE VIRTUAL TABLE IF NOT EXISTS code_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
CREATE VIRTUAL TABLE IF NOT EXISTS line_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
CREATE VIRTUAL TABLE IF NOT EXISTS symbol_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
CREATE VIRTUAL TABLE IF NOT EXISTS route_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
CREATE VIRTUAL TABLE IF NOT EXISTS commit_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
CREATE VIRTUAL TABLE IF NOT EXISTS artifact_fts USING fts5(entity_type, entity_id, file_id, file_version_id, commit_sha, sha256, text);
